modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/BeansCraftDev/Modrinth-mods/issues"
license="GPLv3"

[[mods]]
modId="bcc"
# The Implementation-Version property in the jar's MANIFEST.MF file will be used as the mod version at runtime
version="1.0.0"
displayName="BeansCraftLib"
#updateJSONURL=""
displayURL=""
logoFile="icon.png"
credits="V_SABITRON, squiddev"
authors="Pika"
description='''
Collection of mods for the BeansCraft modpack that are only on Modrinth.'''

[[dependencies.bcc]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.bcc]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.bcc]]
modId="bio-delight"
mandatory=true
versionRange="[1.0.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.bcc]]
modId="cc-tweaked"
mandatory=true
versionRange="[1.114.2,)"
ordering="AFTER"
side="BOTH"
